### ISSUE TITLE
T2, Ej. 5: Pregunta sobre los vértices del triángulo.

### ISSUE THREAD

**Issue by carranco-sga** [lbenet/2020-2-TSelFisicaComputacional-1#26]
Hola a todos,

Una pregunta respecto a la definición del triángulo para el ejercicio 5: ¿el punto A es (1, 0), de tal forma que se forma un triángulo escaleno, o es (0, 1), de tal forma que se forma un triángulo equilátero?

Gracias.

**Comment by lbenet** [comment]
En efecto: el punto A debería estar en (0,1) en lugar de lo que puse. Eso hace el resultado más simétrico y bonito, pero "la estructura" no cambia de manera vital. 
Si quieres, haz el cambio en el enunciado del probblema.

**Comment by carranco-sga** [comment]
Gracias, Luis.
